name: nerdle CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get install pip
          pip3 install --user meson ninja
      - name: Build
        run: |
          meson build
          cd build
          ninja
      - name: Test
        run: |
          cd build
          ninja test
